# Generated by Django 2.1 on 2018-08-22 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='homeImagens',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=150, verbose_name='Titulo')),
                ('sub_titulo', models.CharField(max_length=150, verbose_name='Sub Titulo')),
                ('imagem', models.ImageField(upload_to='media')),
                ('status', models.CharField(choices=[('', 'Selecione'), ('Ativo', 'Ativo'), ('Inativo', 'Inativo')], default='', max_length=10, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Imagens',
                'verbose_name_plural': 'Imagens',
            },
        ),
    ]
