# Generated by Django 2.1 on 2018-08-22 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ongoing',
            fields=[
                ('descricao_item_contabil', models.CharField(max_length=500)),
                ('item_contabil', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True)),
                ('hora_normal', models.IntegerField()),
                ('hora_75_pc', models.IntegerField()),
                ('hora_100_pc', models.IntegerField()),
                ('hora_total', models.IntegerField()),
                ('periodo', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'painel_ongoing_ongoing',
                'managed': False,
            },
        ),
    ]
