# Generated by Django 2.1 on 2018-08-22 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cod_atividade', models.CharField(max_length=5, unique=True, verbose_name='Código')),
                ('des_atividade', models.CharField(max_length=150, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Atividade',
                'verbose_name_plural': 'Atividades',
            },
        ),
        migrations.CreateModel(
            name='ItemContabil',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cod_item_contabil', models.CharField(max_length=5, unique=True, verbose_name='Código')),
                ('des_item_contabil', models.CharField(max_length=150, verbose_name='Descrição')),
                ('cod_tipo_item_contabil', models.CharField(choices=[('GNS', 'GNS'), ('GSR', 'GSR')], max_length=3)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.Clientes', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Item Contabil',
                'verbose_name_plural': 'Itens Contabeis',
            },
        ),
        migrations.AddField(
            model_name='atividade',
            name='cod_item_contabil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro_financeiro.ItemContabil', verbose_name='Item Contabil'),
        ),
    ]
