# Generated by Django 2.1 on 2018-08-22 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FalhasEmAberto',
            fields=[
                ('numero_ocorrencia', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('titulo', models.CharField(max_length=100)),
                ('grupo_suporte', models.CharField(max_length=100)),
                ('tipo_servico', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'vw_painel_falhas_em_aberto_logstash',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FalhasEncerradasNosUltimos6Meses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ocorrencia', models.CharField(max_length=100, unique=True)),
                ('titulo', models.CharField(max_length=100)),
                ('grupo_suporte', models.CharField(max_length=100)),
                ('tipo_servico', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'vw_painel_falhas_encerredas_nos_ultimos_6_meses_logstash',
                'managed': False,
            },
        ),
    ]
