# Generated by Django 2.1 on 2018-08-22 02:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GMUDS',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Data')),
                ('servico', models.CharField(blank=True, max_length=75, verbose_name='Serviço')),
                ('responsavel', models.CharField(blank=True, max_length=75, verbose_name='Responsável')),
                ('titulo', models.CharField(blank=True, max_length=75, verbose_name='Título')),
                ('status', models.CharField(blank=True, choices=[('Ativa', 'Ativa'), ('Inativa', 'Inativa')], max_length=75, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.Clientes', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Painel de GMUDs',
                'verbose_name_plural': 'GMUDs',
            },
        ),
    ]
