# Generated by Django 2.1 on 2018-08-22 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DEMANDAS',
            fields=[
                ('tipo', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('servico', models.CharField(max_length=255)),
                ('data', models.CharField(max_length=255)),
                ('quantidade', models.DecimalField(decimal_places=0, max_digits=5, max_length=35)),
                ('situacao', models.CharField(max_length=255)),
                ('severidade', models.CharField(max_length=255)),
            ],
            options={
                'db_table': '"PAINEIS_GNS"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DEMANDAS_ORDERED',
            fields=[
                ('servico', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('INTERNAS', models.CharField(max_length=255)),
                ('EXTERNAS', models.CharField(max_length=255)),
                ('TOTAL', models.CharField(max_length=255)),
                ('HORAS_EXTERNAS', models.IntegerField()),
                ('HORAS_INTERNAS', models.IntegerField()),
                ('HORAS_TOTAL', models.IntegerField()),
            ],
            options={
                'db_table': 'vw_painel_demandas_logstash',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetailsDemandas',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('tipo_servico', models.CharField(max_length=100)),
                ('severidade', models.CharField(max_length=36)),
                ('quantidade', models.CharField(max_length=100)),
                ('numero_ocorrencia', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=200)),
                ('data_criacao', models.CharField(max_length=100)),
                ('data_solucao', models.CharField(max_length=100)),
                ('grupo_suporte', models.CharField(max_length=100)),
                ('situacao', models.CharField(max_length=100)),
                ('responsavel', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'painel_demandas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalheDemandas',
            fields=[
                ('tipo_servico', models.CharField(max_length=100)),
                ('severidade', models.CharField(max_length=36)),
                ('numero_ocorrencia', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('data_criacao', models.CharField(max_length=100)),
                ('data_solucao', models.CharField(max_length=100)),
                ('grupo_suporte', models.CharField(max_length=100)),
                ('situacao', models.CharField(max_length=100)),
                ('responsavel', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('servico', models.CharField(max_length=100)),
                ('horas_previstas', models.IntegerField()),
            ],
            options={
                'db_table': 'painel_demandas_logstash',
                'managed': False,
            },
        ),
    ]
