# Generated by Django 2.1 on 2018-08-22 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('painel_demandas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='demandas',
            table='painel_demandas_logstash',
        ),
    ]
