# Generated by Django 2.1 on 2018-08-22 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contrato', models.CharField(max_length=155, unique=True, verbose_name='Contrato')),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('departamento', models.CharField(choices=[('DEPTO ADMINISTRATIVO', 'DEPTO ADMINISTRATIVO'), ('DEPTO DA CENTRAL DE SERVICOS', 'DEPTO DA CENTRAL DE SERVICOS'), ('DEPTO DE ATENDIMENTO E SUPORTE', 'DEPTO DE ATENDIMENTO E SUPORTE'), ('DEPTO DE CONTRATOS', 'DEPTO DE CONTRATOS'), ('DEPTO DE DESENVOLVIMENTO', 'DEPTO DE DESENVOLVIMENTO'), ('DEPTO DE ENGENHARIA DE PRODUCAO', 'DEPTO DE ENGENHARIA DE PRODUCAO'), ('DEPTO DE NOVOS NEGOCIOS', 'DEPTO DE NOVOS NEGOCIOS'), ('DEPTO DE OPERACOES DE SERVICOS', 'DEPTO DE OPERACOES DE SERVICOS'), ('DEPTO DE PROCESSOS INTERNOS', 'DEPTO DE PROCESSOS INTERNOS'), ('DEPTO DE PROJETOS', 'DEPTO DE PROJETOS'), ('DEPTO DE PROJETOS DE OPERACOES', 'DEPTO DE PROJETOS DE OPERACOES'), ('DEPTO DE RECURSOS HUMANOS', 'DEPTO DE RECURSOS HUMANOS'), ('DEPTO DE SERVICOS', 'DEPTO DE SERVICOS'), ('DIRETOR DE OPERACOES', 'DIRETOR DE OPERACOES'), ('DIRETORIA ADM./FINANCEIRA', 'DIRETORIA ADM./FINANCEIRA'), ('FINANCEIRO/CONTABIL', 'FINANCEIRO/CONTABIL'), ('GERENCIA DE NOVOS SERVICOS', 'GERENCIA DE NOVOS SERVICOS'), ('GERENCIA DE PROCESSOS E QUALIDADE(GPQ)', 'GERENCIA DE PROCESSOS E QUALIDADE(GPQ)'), ('GERENCIA DE PROJETOS E SOLUCOES (GPS)', 'GERENCIA DE PROJETOS E SOLUCOES (GPS)'), ('GERENCIA DE SERVICOS REGULADOS', 'GERENCIA DE SERVICOS REGULADOS'), ('GERENCIA DE SUPORTE E SERVICOS (GSS)', 'GERENCIA DE SUPORTE E SERVICOS (GSS)'), ('JURIDICO', 'JURIDICO'), ('NEGOCIOS', 'NEGOCIOS'), ('PRESIDENCIA', 'PRESIDENCIA'), ('PRODUCAO', 'PRODUCAO'), ('TEC.INFORMACAO', 'TEC.INFORMACAO')], max_length=155, unique=True, verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
            },
        ),
        migrations.CreateModel(
            name='Funcao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('funcao', models.CharField(choices=[('ADVOGADO JR', 'ADVOGADO JR'), ('AN CONTROLADORIA SR', 'AN CONTROLADORIA SR'), ('ANAL SUP JR - N. I', 'ANAL SUP JR - N. I'), ('ANAL SUP PL - N. I', 'ANAL SUP PL - N. I'), ('ANAL.CONT.FISC JR', 'ANAL.CONT.FISC JR'), ('ANAL.DE MARKETING PL', 'ANAL.DE MARKETING PL'), ('ANAL.SUP JR - N. II', 'ANAL.SUP JR - N. II'), ('ANAL.SUP. PL - N. II', 'ANAL.SUP. PL - N. II'), ('ANALIST COMERCIAL SR', 'ANALIST COMERCIAL SR'), ('ANALISTA DE BANCO DE DADOS SR', 'ANALISTA DE BANCO DE DADOS SR'), ('ANALISTA DE SIST. PL', 'ANALISTA DE SIST. PL'), ('ANALISTA DE SIST. SR', 'ANALISTA DE SIST. SR'), ('ANALISTA DE TESTE JR', 'ANALISTA DE TESTE JR'), ('ANALISTA DE TI PL', 'ANALISTA DE TI PL'), ('ANALISTA DE TI SR', 'ANALISTA DE TI SR'), ('ANALISTA DESENV.JR', 'ANALISTA DESENV.JR'), ('ANALISTA DESENV.PL', 'ANALISTA DESENV.PL'), ('ANALISTA DESENV.SR', 'ANALISTA DESENV.SR'), ('ANALISTA FINANC. JR', 'ANALISTA FINANC. JR'), ('ANALISTA FINANC. PL', 'ANALISTA FINANC. PL'), ('ANALISTA FINANC. SR', 'ANALISTA FINANC. SR'), ('ANALISTA H. DESK JR', 'ANALISTA H. DESK JR'), ('ANALISTA INFRA PL', 'ANALISTA INFRA PL'), ('ANALISTA NEGOCIOS PL', 'ANALISTA NEGOCIOS PL'), ('ANALISTA NEGOCIOS SR', 'ANALISTA NEGOCIOS SR'), ('ANALISTA PROC. PL', 'ANALISTA PROC. PL'), ('ANALISTA PRODUC. SR', 'ANALISTA PRODUC. SR'), ('ANALISTA PRODUC.JR', 'ANALISTA PRODUC.JR'), ('ANALISTA PRODUC.PL', 'ANALISTA PRODUC.PL'), ('ANALISTA PRODUT.SR', 'ANALISTA PRODUT.SR'), ('ANALISTA PROJ. PL', 'ANALISTA PROJ. PL'), ('ANALISTA PROJ. SR', 'ANALISTA PROJ. SR'), ('ANALISTA RH JR', 'ANALISTA RH JR'), ('ANALISTA RH PL', 'ANALISTA RH PL'), ('ASSIST DIRETORIA EXE', 'ASSIST DIRETORIA EXE'), ('ASSIST.DE DESENV.SIS', 'ASSIST.DE DESENV.SIS'), ('AUX.ADMINISTRATIVO', 'AUX.ADMINISTRATIVO'), ('AUXILIAR DE SUPORTE', 'AUXILIAR DE SUPORTE'), ('CONS. DESENVOLVEDOR', 'CONS. DESENVOLVEDOR'), ('CONS. INTERCONEXAO', 'CONS. INTERCONEXAO'), ('CONS. SERV. SUPORTE', 'CONS. SERV. SUPORTE'), ('CONS. SERV. SUPORTE', 'CONS. SERV. SUPORTE'), ('CONSULTOR SIST. TI', 'CONSULTOR SIST. TI'), ('COORD DE SISTEMAS', 'COORD DE SISTEMAS'), ('COORD SERVICOS T.I.', 'COORD SERVICOS T.I.'), ('COORD. DE PROJETOS', 'COORD. DE PROJETOS'), ('COORD. TEC. INFORM.', 'COORD. TEC. INFORM.'), ('COORDENADOR FISCAL', 'COORDENADOR FISCAL'), ('COORDENADOR SUPORTE', 'COORDENADOR SUPORTE'), ('DIRETOR COMERCIAL', 'DIRETOR COMERCIAL'), ('DIRETOR DE OPERACOES', 'DIRETOR DE OPERACOES'), ('ESPEC DES.SISTEMAS', 'ESPEC DES.SISTEMAS'), ('ESTAGIARIO', 'ESTAGIARIO'), ('GER PROC E QUALIDADE', 'GER PROC E QUALIDADE'), ('GER PROJ E SOLUCOES', 'GER PROJ E SOLUCOES'), ('GER SUP E SERVICOS', 'GER SUP E SERVICOS'), ('GER.CONT.INT.E COMPL', 'GER.CONT.INT.E COMPL'), ('GER.TEC. INFORMACAO', 'GER.TEC. INFORMACAO'), ('GERENTE DE CONTAS"', 'GERENTE DE CONTAS')], max_length=155, unique=True, verbose_name='Função')),
                ('valor_hora', models.DecimalField(decimal_places=2, default='150', max_digits=10, verbose_name='Valor Hora')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcionarios.Contrato')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcionarios.Departamento')),
            ],
            options={
                'verbose_name': 'Função',
                'verbose_name_plural': 'Funções',
            },
        ),
    ]
