# Generated by Django 2.1 on 2018-08-22 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('painel_horas_gns', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='resumorateiohorasgns',
            table='painel_rateio_horas_por_ic_ativ_logstash',
        ),
    ]
