# Generated by Django 2.1 on 2018-08-22 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro_financeiro', '0001_initial'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HORAS_OPORTUNIDADES',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('item_contabil', models.CharField(max_length=255)),
                ('hora_total', models.CharField(max_length=255)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OPORTUNIDADES',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('oportunidade', models.CharField(blank=True, max_length=75, verbose_name='Oportunidade')),
                ('status', models.CharField(blank=True, choices=[('Prospecção de novos negócios', 'Prospecção de novos negócios'), ('Desenvolvimento de Proposta', 'Desenvolvimento de Proposta'), ('Proposta Enviada', 'Proposta Enviada'), ('Finalizada', 'Finalizada')], max_length=75, null=True)),
                ('justificativa', models.TextField(blank=True, verbose_name='Justificativa Status')),
                ('responsavel', models.CharField(blank=True, max_length=75, verbose_name='Responsável')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('historico', models.TextField(blank=True, verbose_name='Histórico')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.Clientes', verbose_name='Cliente')),
                ('codigo_atividade', models.ManyToManyField(to='cadastro_financeiro.Atividade', verbose_name='Cód. Atividade')),
                ('item_contabil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro_financeiro.ItemContabil', verbose_name='Item Contábil')),
            ],
            options={
                'verbose_name': 'Painel de Oportunidades',
                'verbose_name_plural': 'Oportunidades',
            },
        ),
    ]
