# Generated by Django 2.1 on 2018-08-22 02:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro_financeiro', '0001_initial'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='receitas_extras_ongoing_operadoras',
            fields=[
                ('ano_mes', models.IntegerField()),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cliente', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'receitas_extras_ongoing_operadoras',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReceitasExtrasOngoing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_atividade', models.CharField(choices=[('ARS', 'ARS'), ('PRJ', 'PRJ'), ('STI', 'STI'), ('Outros', 'Outros'), ('Change Request', 'Change Request')], max_length=75, verbose_name='Tipo Atividade')),
                ('identificador_atividade', models.CharField(max_length=75, verbose_name='Identificador Atividade')),
                ('data', models.DateField(default=datetime.date.today, verbose_name='Data')),
                ('valor_orcado', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Valor Orçado')),
                ('horas_orcadas', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Horas Orçadas')),
                ('previsao_faturamento', models.TextField(blank=True, null=True, verbose_name='Previsão Faturamento')),
                ('impacto_ongoing', models.TextField(blank=True, null=True, verbose_name='Impacto Ongoing')),
                ('implementado', models.TextField(blank=True, null=True, verbose_name='Implementado')),
                ('data_implatacao', models.DateField(blank=True, null=True, verbose_name='Data Implantação')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.Clientes')),
                ('item_contabil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro_financeiro.ItemContabil')),
            ],
        ),
    ]
