# Generated by Django 2.1 on 2018-08-22 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ORCAMENTOS_PORCENTAGEM_BEN',
            fields=[
                ('tipo_despesa', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('descricao_natureza', models.CharField(max_length=255)),
                ('valor', models.CharField(max_length=255)),
                ('perc', models.CharField(max_length=255)),
                ('valor_total', models.CharField(max_length=255)),
            ],
            options={
                'db_table': '"PAINEL_ORCAMENTOS_PORC_BEN"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ORCAMENTOS_PORCENTAGEM_CAP',
            fields=[
                ('tipo_despesa', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('descricao_natureza', models.CharField(max_length=255)),
                ('valor', models.CharField(max_length=255)),
                ('perc', models.CharField(max_length=255)),
                ('valor_total', models.CharField(max_length=255)),
            ],
            options={
                'db_table': '"PAINEL_ORCAMENTOS_PORC_CAP"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ORCAMENTOS_PORCENTAGEM_CON',
            fields=[
                ('tipo_despesa', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('descricao_natureza', models.CharField(max_length=255)),
                ('valor', models.CharField(max_length=255)),
                ('perc', models.CharField(max_length=255)),
                ('valor_total', models.CharField(max_length=255)),
            ],
            options={
                'db_table': '"PAINEL_ORCAMENTOS_PORC_CON"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ORCAMENTOS_PORCENTAGEM_EVE',
            fields=[
                ('tipo_despesa', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('descricao_natureza', models.CharField(max_length=255)),
                ('valor', models.CharField(max_length=255)),
                ('perc', models.CharField(max_length=255)),
                ('valor_total', models.CharField(max_length=255)),
            ],
            options={
                'db_table': '"PAINEL_ORCAMENTOS_PORC_EVE"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ORCAMENTOS_PORCENTAGEM_FOR',
            fields=[
                ('tipo_despesa', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('descricao_natureza', models.CharField(max_length=255)),
                ('valor', models.CharField(max_length=255)),
                ('perc', models.CharField(max_length=255)),
                ('valor_total', models.CharField(max_length=255)),
            ],
            options={
                'db_table': '"PAINEL_ORCAMENTOS_PORC_FOR"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ORCAMENTOS_PORCENTAGEM_SEM',
            fields=[
                ('tipo_despesa', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('descricao_natureza', models.CharField(max_length=255)),
                ('valor', models.CharField(max_length=255)),
                ('perc', models.CharField(max_length=255)),
                ('valor_total', models.CharField(max_length=255)),
            ],
            options={
                'db_table': '"PAINEL_ORCAMENTOS_PORC_SEM"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ORCAMENTOS_PORCENTAGEM_VIG',
            fields=[
                ('tipo_despesa', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('descricao_natureza', models.CharField(max_length=255)),
                ('valor', models.CharField(max_length=255)),
                ('perc', models.CharField(max_length=255)),
                ('valor_total', models.CharField(max_length=255)),
            ],
            options={
                'db_table': '"PAINEL_ORCAMENTOS_PORC_VIG"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ORCAMENTOS_RELAZIADOS',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ano_mes', models.CharField(max_length=255)),
                ('tipo_despesa', models.CharField(max_length=255)),
                ('descricao_natureza', models.CharField(max_length=255)),
                ('centro_de_custo', models.DecimalField(decimal_places=0, max_digits=5, max_length=35)),
                ('item_contabil', models.CharField(max_length=255)),
                ('descricao_item', models.CharField(max_length=255)),
                ('valor', models.CharField(max_length=255)),
            ],
            options={
                'db_table': '"PAINEL_ORCAMENTOS_GNS"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PainelOrcamentosLogstash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=6, unique=True)),
                ('grupo_despesa', models.CharField(max_length=255)),
                ('cod_natureza', models.IntegerField(unique=True)),
                ('descricao_natureza', models.CharField(max_length=30)),
                ('centro_custo', models.CharField(max_length=5, unique=True)),
                ('item_contabil', models.CharField(max_length=5, unique=True)),
                ('descricao_item', models.CharField(max_length=40)),
                ('valor_aprovado', models.DecimalField(decimal_places=2, max_digits=20)),
                ('valor_acumulado_mes', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
            options={
                'db_table': 'painel_orcamentos_logstash',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ORCAMENTOS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('despesa', models.CharField(choices=[('Beneficios', 'Beneficios'), ('Capacitacoes', 'Capacitacoes'), ('Consumos', 'Consumos'), ('Eventos', 'Eventos'), ('Fornecedores', 'Fornecedores'), ('Viagens', 'Viagens'), ('Sem Classificacao', 'Sem Classificacao')], default='Sem Classificação', max_length=30)),
                ('mes', models.CharField(max_length=2, null=True)),
                ('ano', models.CharField(max_length=4, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Valor Previsto')),
                ('valor_realizado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Realizado')),
                ('valor_projetado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Projetado')),
            ],
            options={
                'verbose_name': 'Orçamento',
                'verbose_name_plural': 'Orçamentos',
            },
        ),
        migrations.CreateModel(
            name='OrcamentosAcumulado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_mes', models.CharField(max_length=6)),
                ('valor_saldo', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('valor_aprovado', models.DecimalField(decimal_places=2, max_digits=20)),
                ('valor_previsto', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='orcamentos',
            unique_together={('ano', 'mes', 'despesa')},
        ),
    ]
