TYPE=VIEW
query=select `a`.`servico` AS `SERVICO`,(select ifnull(sum(`b`.`quantidade`),0) from (select count(0) AS `quantidade`,`a`.`tipo_servico` AS `servico`,`a`.`situacao` AS `situacao` from `sarg`.`vw_painel_ocorrencias_em_aberto_logstash` `a` group by `a`.`tipo_servico`,`a`.`situacao`) `b` where ((`b`.`servico` = `a`.`servico`) and (`b`.`situacao` = \'Aguardando o solicitante\'))) AS `AGUARDANDO`,(select ifnull(sum(`c`.`quantidade`),0) from (select count(0) AS `quantidade`,`a`.`tipo_servico` AS `servico`,`a`.`situacao` AS `situacao` from `sarg`.`vw_painel_ocorrencias_em_aberto_logstash` `a` group by `a`.`tipo_servico`,`a`.`situacao`) `c` where ((`c`.`servico` = `a`.`servico`) and (`c`.`situacao` = \'Em atendimento\'))) AS `ATENDIMENTO`,(select ifnull(sum(`c`.`quantidade`),0) from (select count(0) AS `quantidade`,`a`.`tipo_servico` AS `servico`,`a`.`situacao` AS `situacao` from `sarg`.`vw_painel_ocorrencias_em_aberto_logstash` `a` group by `a`.`tipo_servico`,`a`.`situacao`) `c` where ((`c`.`servico` = `a`.`servico`) and (`c`.`situacao` = \'Encaminhada\'))) AS `ENCAMINHADO`,(select ifnull(sum(`d`.`quantidade`),0) from (select count(0) AS `quantidade`,`a`.`tipo_servico` AS `servico`,`a`.`situacao` AS `situacao` from `sarg`.`vw_painel_ocorrencias_em_aberto_logstash` `a` group by `a`.`tipo_servico`,`a`.`situacao`) `d` where ((`d`.`servico` = `a`.`servico`) and (`d`.`situacao` in (\'Aguardando o solicitante\',\'Em atendimento\',\'Encaminhada\')))) AS `TOTAL` from (select count(0) AS `quantidade`,`a`.`tipo_servico` AS `servico`,`a`.`situacao` AS `situacao` from `sarg`.`vw_painel_ocorrencias_em_aberto_logstash` `a` group by `a`.`tipo_servico`,`a`.`situacao`) `a` group by `a`.`servico` order by `TOTAL` desc
md5=ef942de1ff06806b9d37de9c7e38f4e7
updatable=0
algorithm=0
definer_user=root
definer_host=%
suid=1
with_check_option=0
timestamp=2018-10-09 15:22:19
create-version=1
source=SELECT \n        `a`.`servico` AS `SERVICO`,\n        (SELECT \n                IFNULL(SUM(`b`.`quantidade`), 0)\n            FROM\n                (SELECT \n                    COUNT(0) AS `quantidade`,\n                        `a`.`tipo_servico` AS `servico`,\n                        `a`.`situacao` AS `situacao`\n                FROM\n                    `sarg`.`vw_painel_ocorrencias_em_aberto_logstash` `a`\n                GROUP BY `a`.`tipo_servico` , `a`.`situacao`) `b`\n            WHERE\n                ((`b`.`servico` = `a`.`servico`)\n                    AND (`b`.`situacao` = \'Aguardando o solicitante\'))) AS `AGUARDANDO`,\n        (SELECT \n                IFNULL(SUM(`c`.`quantidade`), 0)\n            FROM\n                (SELECT \n                    COUNT(0) AS `quantidade`,\n                        `a`.`tipo_servico` AS `servico`,\n                        `a`.`situacao` AS `situacao`\n                FROM\n                    `sarg`.`vw_painel_ocorrencias_em_aberto_logstash` `a`\n                GROUP BY `a`.`tipo_servico` , `a`.`situacao`) `c`\n            WHERE\n                ((`c`.`servico` = `a`.`servico`)\n                    AND (`c`.`situacao` = \'Em atendimento\'))) AS `ATENDIMENTO`,\n        (SELECT \n                IFNULL(SUM(`c`.`quantidade`), 0)\n            FROM\n                (SELECT \n                    COUNT(0) AS `quantidade`,\n                        `a`.`tipo_servico` AS `servico`,\n                        `a`.`situacao` AS `situacao`\n                FROM\n                    `sarg`.`vw_painel_ocorrencias_em_aberto_logstash` `a`\n                GROUP BY `a`.`tipo_servico` , `a`.`situacao`) `c`\n            WHERE\n                ((`c`.`servico` = `a`.`servico`)\n                    AND (`c`.`situacao` = \'Encaminhada\'))) AS `ENCAMINHADO`,\n        (SELECT \n                IFNULL(SUM(`d`.`quantidade`), 0)\n            FROM\n                (SELECT \n                    COUNT(0) AS `quantidade`,\n                        `a`.`tipo_servico` AS `servico`,\n                        `a`.`situacao` AS `situacao`\n                FROM\n                    `sarg`.`vw_painel_ocorrencias_em_aberto_logstash` `a`\n                GROUP BY `a`.`tipo_servico` , `a`.`situacao`) `d`\n            WHERE\n                ((`d`.`servico` = `a`.`servico`)\n                    AND (`d`.`situacao` IN (\'Aguardando o solicitante\' , \'Em atendimento\', \'Encaminhada\')))) AS `TOTAL`\n    FROM\n        (SELECT \n            COUNT(0) AS `quantidade`,\n                `a`.`tipo_servico` AS `servico`,\n                `a`.`situacao` AS `situacao`\n        FROM\n            `sarg`.`vw_painel_ocorrencias_em_aberto_logstash` `a`\n        GROUP BY `a`.`tipo_servico` , `a`.`situacao`) `a`\n    GROUP BY `a`.`servico`\n    ORDER BY `TOTAL` DESC
client_cs_name=latin1
connection_cl_name=latin1_swedish_ci
view_body_utf8=select `a`.`servico` AS `SERVICO`,(select ifnull(sum(`b`.`quantidade`),0) from (select count(0) AS `quantidade`,`a`.`tipo_servico` AS `servico`,`a`.`situacao` AS `situacao` from `sarg`.`vw_painel_ocorrencias_em_aberto_logstash` `a` group by `a`.`tipo_servico`,`a`.`situacao`) `b` where ((`b`.`servico` = `a`.`servico`) and (`b`.`situacao` = \'Aguardando o solicitante\'))) AS `AGUARDANDO`,(select ifnull(sum(`c`.`quantidade`),0) from (select count(0) AS `quantidade`,`a`.`tipo_servico` AS `servico`,`a`.`situacao` AS `situacao` from `sarg`.`vw_painel_ocorrencias_em_aberto_logstash` `a` group by `a`.`tipo_servico`,`a`.`situacao`) `c` where ((`c`.`servico` = `a`.`servico`) and (`c`.`situacao` = \'Em atendimento\'))) AS `ATENDIMENTO`,(select ifnull(sum(`c`.`quantidade`),0) from (select count(0) AS `quantidade`,`a`.`tipo_servico` AS `servico`,`a`.`situacao` AS `situacao` from `sarg`.`vw_painel_ocorrencias_em_aberto_logstash` `a` group by `a`.`tipo_servico`,`a`.`situacao`) `c` where ((`c`.`servico` = `a`.`servico`) and (`c`.`situacao` = \'Encaminhada\'))) AS `ENCAMINHADO`,(select ifnull(sum(`d`.`quantidade`),0) from (select count(0) AS `quantidade`,`a`.`tipo_servico` AS `servico`,`a`.`situacao` AS `situacao` from `sarg`.`vw_painel_ocorrencias_em_aberto_logstash` `a` group by `a`.`tipo_servico`,`a`.`situacao`) `d` where ((`d`.`servico` = `a`.`servico`) and (`d`.`situacao` in (\'Aguardando o solicitante\',\'Em atendimento\',\'Encaminhada\')))) AS `TOTAL` from (select count(0) AS `quantidade`,`a`.`tipo_servico` AS `servico`,`a`.`situacao` AS `situacao` from `sarg`.`vw_painel_ocorrencias_em_aberto_logstash` `a` group by `a`.`tipo_servico`,`a`.`situacao`) `a` group by `a`.`servico` order by `TOTAL` desc
