TYPE=VIEW
query=select `sarg`.`painel_demandas_logstash`.`consulta` AS `consulta`,`sarg`.`painel_demandas_logstash`.`numero_ocorrencia` AS `numero_ocorrencia`,`sarg`.`painel_demandas_logstash`.`titulo` AS `titulo`,`sarg`.`painel_demandas_logstash`.`data_criacao` AS `data_criacao`,`sarg`.`painel_demandas_logstash`.`data_solucao` AS `data_solucao`,`sarg`.`painel_demandas_logstash`.`grupo_suporte` AS `grupo_suporte`,`sarg`.`painel_demandas_logstash`.`tipo_servico` AS `tipo_servico`,`sarg`.`painel_demandas_logstash`.`situacao` AS `situacao`,`sarg`.`painel_demandas_logstash`.`severidade` AS `severidade`,`sarg`.`painel_demandas_logstash`.`responsavel` AS `responsavel`,`sarg`.`painel_demandas_logstash`.`tipo` AS `tipo`,`sarg`.`painel_demandas_logstash`.`servico` AS `servico`,`sarg`.`painel_demandas_logstash`.`horas_previstas` AS `horas_previstas`,`sarg`.`painel_demandas_logstash`.`qtde_hrs_realizada` AS `qtde_hrs_realizada` from `sarg`.`painel_demandas_logstash` where (`sarg`.`painel_demandas_logstash`.`consulta` = (select max(`sarg`.`painel_demandas_logstash`.`consulta`) from `sarg`.`painel_demandas_logstash`))
md5=4fe04be2cde463049d22514d7712c0e4
updatable=0
algorithm=0
definer_user=root
definer_host=%
suid=1
with_check_option=0
timestamp=2018-10-09 15:22:19
create-version=1
source=SELECT \n        `sarg`.`painel_demandas_logstash`.`consulta` AS `consulta`,\n        `sarg`.`painel_demandas_logstash`.`numero_ocorrencia` AS `numero_ocorrencia`,\n        `sarg`.`painel_demandas_logstash`.`titulo` AS `titulo`,\n        `sarg`.`painel_demandas_logstash`.`data_criacao` AS `data_criacao`,\n        `sarg`.`painel_demandas_logstash`.`data_solucao` AS `data_solucao`,\n        `sarg`.`painel_demandas_logstash`.`grupo_suporte` AS `grupo_suporte`,\n        `sarg`.`painel_demandas_logstash`.`tipo_servico` AS `tipo_servico`,\n        `sarg`.`painel_demandas_logstash`.`situacao` AS `situacao`,\n        `sarg`.`painel_demandas_logstash`.`severidade` AS `severidade`,\n        `sarg`.`painel_demandas_logstash`.`responsavel` AS `responsavel`,\n        `sarg`.`painel_demandas_logstash`.`tipo` AS `tipo`,\n        `sarg`.`painel_demandas_logstash`.`servico` AS `servico`,  \n        `sarg`.`painel_demandas_logstash`.`horas_previstas` AS `horas_previstas`,\n        `sarg`.`painel_demandas_logstash`.`qtde_hrs_realizada` AS `qtde_hrs_realizada`\n              \n    FROM\n        `sarg`.`painel_demandas_logstash`\n    WHERE\n        (`sarg`.`painel_demandas_logstash`.`consulta` = (SELECT \n                MAX(`sarg`.`painel_demandas_logstash`.`consulta`)\n            FROM\n                `sarg`.`painel_demandas_logstash`))
client_cs_name=latin1
connection_cl_name=latin1_swedish_ci
view_body_utf8=select `sarg`.`painel_demandas_logstash`.`consulta` AS `consulta`,`sarg`.`painel_demandas_logstash`.`numero_ocorrencia` AS `numero_ocorrencia`,`sarg`.`painel_demandas_logstash`.`titulo` AS `titulo`,`sarg`.`painel_demandas_logstash`.`data_criacao` AS `data_criacao`,`sarg`.`painel_demandas_logstash`.`data_solucao` AS `data_solucao`,`sarg`.`painel_demandas_logstash`.`grupo_suporte` AS `grupo_suporte`,`sarg`.`painel_demandas_logstash`.`tipo_servico` AS `tipo_servico`,`sarg`.`painel_demandas_logstash`.`situacao` AS `situacao`,`sarg`.`painel_demandas_logstash`.`severidade` AS `severidade`,`sarg`.`painel_demandas_logstash`.`responsavel` AS `responsavel`,`sarg`.`painel_demandas_logstash`.`tipo` AS `tipo`,`sarg`.`painel_demandas_logstash`.`servico` AS `servico`,`sarg`.`painel_demandas_logstash`.`horas_previstas` AS `horas_previstas`,`sarg`.`painel_demandas_logstash`.`qtde_hrs_realizada` AS `qtde_hrs_realizada` from `sarg`.`painel_demandas_logstash` where (`sarg`.`painel_demandas_logstash`.`consulta` = (select max(`sarg`.`painel_demandas_logstash`.`consulta`) from `sarg`.`painel_demandas_logstash`))
