# Generated by Django 2.1 on 2018-08-22 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RateioHoras',
            fields=[
                ('id_func', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('semana_1', models.CharField(max_length=13)),
                ('semana_2', models.CharField(max_length=13)),
                ('semana_3', models.CharField(max_length=13)),
                ('semana_4', models.CharField(max_length=13)),
                ('semana_5', models.CharField(max_length=13)),
                ('periodo', models.CharField(max_length=100)),
                ('estatus', models.CharField(max_length=10)),
                ('ultima_semana_periodo', models.IntegerField()),
            ],
            options={
                'db_table': 'painel_rateio_horas_logstash',
                'managed': False,
            },
        ),
    ]
