# Generated by Django 2.1 on 2018-08-22 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('painel_rateio_horas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='rateiohoras',
            table='painel_orcamentos_por_pessoa_logstash',
        ),
    ]
