# Generated by Django 2.1 on 2018-08-22 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('painel_rateio_horas', '0002_auto_20180821_2348'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='rateiohoras',
            table='painel_rateio_horas_por_pessoa_logstash',
        ),
    ]
